blank_issues_enabled: true
contact_links:
  - name: Contributing Guide
    url: https://github.com/michaelpetschel/Horizon-Tools/blob/main/CONTRIBUTING.md
    about: Please read the contributing guide before opening a pull request.
